config/routes.rb
Rails.application.routes.draw do

  get 'shop_images/show'

  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc

  Spree::Core::Engine.routes.draw do
  get 'shop_images/show'

  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc
    root to: "products#index"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount Spree::Core::Engine, :at => '/store'

  root :to => 'jcautohome#home'

  get "/admin" => redirect("/store/admin")

  get 'about' => 'jcautohome#about'
  get 'gallery' => 'jcautohome#gallery'
  get 'parts' => 'jcautohome#parts'
  get 'our-services' => 'jcautohome#services'
  get 'community' => 'jcautohome#community'
  get 'contact' => 'jcautohome#contact'
  get 'our-services/gauges' => 'jcautohome#gauges'
  get 'our-services/em' => 'jcautohome#em'
  get 'our-services/shipping' => 'jcautohome#shipping'
  get 'sale-cars' => 'jcautohome#sale_cars'
  get 'policies' => 'jcautohome#policies'
  get 'privacy-policy' => 'jcautohome#privacy_policy'
  get 'timeline' => 'jcautohome#timeline'
  get 'my-cars' => 'customer_cars#index'

  resources :services, only: :show
  resources :jcautohome do
    collection do
      post :submit_contact
    end
  end

  resources :cars, only: :show
  resources :sale_cars, only: :show
  resources :customer_cars, except: :show
  resources :shop_images, only: :show
  

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  namespace :admin do
    resources :customers do
      resources :contacts do
        member do
          put 'resolved'
        end
      end
    end

    resources :cars do
      resources :car_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :sale_cars do
      resources :sale_car_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :events do
      resources :event_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :stories do
      resources :story_images
    end

    resources :services do
      resources :service_images
      resources :service_price_lists do
        collection do
          post :update_service_items_positions
        end
      end
    end

    resources :shop_images

    delete '/service_items/:id', to: "service_items#destroy", as: :service_item
  end

  resources :events, only: [:index, :show] do
    collection do
      post :event_rsvp
    end
  end

  resources :stories, only: [:index, :show]

  resources :user_events, only: [:create, :new]

end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :service_images
	has_many :service_price_lists
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def edit
  	
  end

  def show

  end

  def new
    @service = Service.new
  end

  def create
      @service = Service.new(service_params)

      respond_to do |format|
      if @service.save
        flash[:success] = "Service was successfully created."
        format.html { redirect_to admin_services_path }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
  	@services = Service.all
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        flash[:success] = "Service was successfully updated."
        format.html { redirect_to admin_services_path }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      flash[:success] = 'Service was successfully destroyed.'
      format.html { redirect_to admin_services_path }
      format.json { head :no_content }
      end
  end

  
  private

  def set_service
  	@service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:name, :description)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @title = "Services - JC Auto Restoration, Inc."
    @services = Service.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    # params[:q] = {} if params[:q].blank?
    @title = "#{@service.name} - JC Auto Restoration, Inc."
  	@service_applications = []
  	@price_lists = @service.service_price_lists
  	@price_lists.each do |price_list|
  		price_list.service_items.order("position ASC").each do |item|
  			if item.service_application && (!@service_applications.include? item.service_application)
  				@service_applications << item.service_application
  			end
  		end
  	end

    # @search = @service_applications.ransack(params[:q])
    # @activities = @search.result.order('created_at desc').page(params[:page]).per(Spree::Config[:admin_products_per_page])

  	if params[:my_service_application]
      if params[:my_service_application][:my_service_application_id]
  		  @service_app_id = params[:my_service_application][:my_service_application_id].to_i
      end
      if params[:my_service_application][:my_service_price_list_id]
        @service_price_list_id = params[:my_service_application][:my_service_price_list_id].to_i
      end
  	end
  end

  # GET /cars/new
  def new
    @service = Service.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, notice: 'Errors uploading the service.' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to service_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params[:service]
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_form.html.erb
<%= form_for [:admin, @service], html: { multipart: true } do |f| %>
  <%= render partial: 'spree/shared/error_messages', locals: { target: @service } %>

    <div class="form-group">
      <%= f.label :name, Spree.t(:name) %>
      <%= f.text_field :name %>
    </div>

    <div class="form-group">
      <%= f.label :description, Spree.t(:description) %>
      <%= f.text_area :description, :rows => 4, :class => 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-success"%>
      <%= link_to 'Back', admin_services_path, class: "btn btn-default" %> 
    </div>
<% end %>

app/views/admin/services/edit.html.erb
<div class="container">
  <div class="row">
  		<div class="col-md-12">
	  		<ol class="breadcrumb" style="text-align: left">
		      <li><%=link_to admin_services_path do %>Services<% end %></li>
		      <li class="active"><%= @service.name %></li>
		    </ol>
		</div>

		<div class="col-md-8">
			<h2><%= @service.name %></h2>
		</div>
		<div class="col-md-4" style="padding-top: 25px">
			<%= link_to 'View Page', @service, class: "btn btn-info" %>
			<%= link_to 'Images', admin_service_service_images_path(@service), class: "btn btn-info" %>
		</div>
		<div class="col-md-12">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/admin/services/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>All Services</h2>
      <p class="intro" style="margin-left: 0; margin-right: 0">List of all our services.</p>
    </div>
    <div class="col-md-4">
      <%= link_to 'New Service', new_admin_service_path, class: "btn btn-primary", style: "margin-top: 26px" %>
    </div>

    <div id="content" class="col-md-12" style="margin-top: 25px">
      <%= flash_messages %>
    </div>

    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Service</th>
            <th>Price Lists</th>
            <th>Number of Images</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @services.each do |service| %>
            <tr>
              <td><%= service.name %></td>
              <td>
              	<ul>
	              	<% service.service_price_lists.each do |list| %>
	              		<li><%= link_to list.name, admin_service_service_price_list_path(service, list) %></li>
	              	<% end %>
              	</ul>
              </td>
              <td><%= service.service_images.length %></td>
              <td><%= link_to 'Page', service %></td>
              <td><%= link_to 'Edit', edit_admin_service_path(service) %></td>
              <td><%= link_to 'Remove', admin_service_path(service), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/services/new.html.erb
<div class="container">
  	<div class="row">
		<h2>New Service</h2>

		<%= render 'form' %>
	</div>
</div>