config/routes.rb
Rails.application.routes.draw do

  get 'shop_images/show'

  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc

  Spree::Core::Engine.routes.draw do
  get 'shop_images/show'

  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc
    root to: "products#index"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount Spree::Core::Engine, :at => '/store'

  root :to => 'jcautohome#home'

  get "/admin" => redirect("/store/admin")

  get 'about' => 'jcautohome#about'
  get 'gallery' => 'jcautohome#gallery'
  get 'parts' => 'jcautohome#parts'
  get 'our-services' => 'jcautohome#services'
  get 'community' => 'jcautohome#community'
  get 'contact' => 'jcautohome#contact'
  get 'our-services/gauges' => 'jcautohome#gauges'
  get 'our-services/em' => 'jcautohome#em'
  get 'our-services/shipping' => 'jcautohome#shipping'
  get 'sale-cars' => 'jcautohome#sale_cars'
  get 'policies' => 'jcautohome#policies'
  get 'privacy-policy' => 'jcautohome#privacy_policy'
  get 'timeline' => 'jcautohome#timeline'
  get 'my-cars' => 'customer_cars#index'

  resources :services, only: :show
  resources :jcautohome do
    collection do
      post :submit_contact
    end
  end

  resources :cars, only: :show
  resources :sale_cars, only: :show
  resources :customer_cars, except: :show
  resources :shop_images, only: :show
  

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  namespace :admin do
    resources :customers do
      resources :contacts do
        member do
          put 'resolved'
        end
      end
    end

    resources :cars do
      resources :car_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :sale_cars do
      resources :sale_car_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :events do
      resources :event_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :stories do
      resources :story_images
    end

    resources :services do
      resources :service_images
      resources :service_price_lists do
        collection do
          post :update_service_items_positions
        end
      end
    end

    resources :shop_images

    delete '/service_items/:id', to: "service_items#destroy", as: :service_item
  end

  resources :events, only: [:index, :show] do
    collection do
      post :event_rsvp
    end
  end

  resources :stories, only: [:index, :show]

  resources :user_events, only: [:create, :new]

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	validate :first_or_last
	# validates :phone, uniqueness: true, scope: :first_name
	# validates :email, uniqueness: true

	before_save :generate_name
	before_save :format_phone

	has_many :contacts, :dependent => :destroy

	# Remove non-digit characters from phone number
	def format_phone
		if self.phone.present?
			self.phone = self.phone.gsub(/\D/, "")
		end
	end

	def generate_name
		my_first_name = self.first_name.present? ? self.first_name : ""
		my_last_name = self.last_name.present? ? self.last_name : ""
		both = (!my_first_name.empty? && !my_last_name.empty?) ? " " : ""
		self.full_name = my_first_name + both + my_last_name
	end

	def first_or_last
		if !first_name? && !last_name?
			errors.add(:base, "Specify first name, last name, or both")
		end
	end

end

app/controllers/admin/customers_controller.rb
module Admin
	class CustomersController < AdminController
		before_action :get_customer, only: [:show, :update, :edit]

		# GET /customers/
		def index
			# Handle phone characters
			if params[:q] && params[:q][:phone]
				params[:q][:phone].gsub!(/\D/, "")
			end

			@search = Customer.ransack(params[:q])
			@customers = @search.result.order(sort_column("customer") + " " + sort_direction).page(params[:page]).per(params[:per_page])
		end

		# GET /customers/:id
		# GET /customers/:id.json
		def show
			@search_contacts = @customer.contacts.ransack(params[:q])
			@contacts = @search_contacts.result.order(sort_column("contact") + " " + sort_direction).page(params[:page]).per(params[:per_page])
		end

		# POST /customers/new
		def new
			@customer = Customer.new
		end

		def create
			@customer = Customer.new(customer_params)

			respond_to do |format|
				if @customer.save
					format.html { redirect_to admin_customer_path(@customer), notice: "Customer was created successfully" }
					format.json { render action: "show", status: :created, location: @customer }
				else
					format.html { render action: "new", error: "Customer could not be created. " + @customer.errors.first[1].to_s }
					format.json { render json: @customer.errors, status: :unprocessable_entity }
				end
			end
		end

		# GET /customers/1/edit
		def edit
		end

		# PUT/PATCH /customers/1/
		def update
			respond_to do |format|
				if @customer.update(customer_params)
					format.html { redirect_to admin_customer_path(@customer), notice: "Customer was updated successfully" }
					format.json { render action: "show", status: :updated, location: @customer }
				else
					format.html { render action: "edit", error: "Customer could not be updated. " + @customer.errors.first[1].to_s }
					format.json { render json: @customer.errors, status: :unprocessable_entity }
				end
			end
		end

		private

		def customer_params
			params.require(:customer).permit(:first_name, :last_name, :email, :phone, :notes, :vehicle, :in_quickbooks)
		end

		def get_customer 
			@customer = Customer.find(params[:id])
		end
	end
end

app/views/admin/customers/_form.html.erb
<%= form_for [:admin, @customer] do |f| %>
	<div class="col-xs-12 col-sm-6 col-md-6">
		<div class="form-group">
			<%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6">
		<div class="form-group">
			<%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6">
		<div class="form-group">
			<%= f.text_field :phone, class: "form-control", placeholder: "Phone" %>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6">
		<div class="form-group">
			<%= f.text_field :email, class: "form-control", placeholder: "Email" %>
		</div>
	</div>
	<div class="col-md-12">
		<div class="form-group">
			<%= f.text_field :vehicle, class: "form-control", placeholder: "Vehicle" %>
		</div>
	</div>
	<div class="col-md-12">
		<div class="form-group">
			<%= f.text_area :notes, class: "form-control", placeholder: "Notes" %>
		</div>
	</div>
	<div class="col-md-12">
		<div class="form-group">
			<%= f.check_box :in_quickbooks %>
			<%= f.label :in_quickbooks %>
		</div>
	</div>
	<div class="col-md-12">
		<%= f.submit class: "btn btn-default" %>
	</div>
<% end %>

app/views/admin/customers/edit.html.erb
<div class="container">
	<div class="row">
		<h2>Edit Customer</h2>
	</div>
	<div class="row">
		<div id="content" class="col-md-12" style="margin-top: 25px">
			<%= flash_messages %>
		</div>
		<%= render "form" %>
	</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h2>Customer Contact Log</h2>
		</div>
		<div class="col-md-4" style="margin-top: 25px">
			<%= link_to "New Customer", new_admin_customer_path, class: "btn btn-default" %>
		</div>
	</div>
	<div class="row">
		<div class="well">
			<%= search_form_for [:admin, @search] do |f| %>
				<div class="col-md-4">
					<div class="form-group">
						<%= f.label :full_name_cont, "Customer Name" %>
						<%= f.text_field :full_name_cont, :size => 15, class: "form-control" %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<%= f.label :phone_cont, "Customer Phone" %>
						<%= f.text_field :phone_cont, :size => 15, class: "form-control" %>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<%= f.label :email_cont, "Customer Email" %>
						<%= f.text_field :email_cont, :size => 15, class: "form-control" %>
					</div>
				</div>
				<div class="col-md-12">
					<%= f.submit class: "btn btn-default" %>
				</div>
			<% end %>
			<div class="clearfix"></div>
		</div>
	</div><!-- Row -->
	<div class="row">
		<div class="col-md-12">
			<% if @customers.empty? %>
				<h2>No customers at this time.</h2>
			<% else %> 
				<div class="table-responsive">
					<table class="table table-striped">
						<thead>
							<tr>
								<th><%= sortable "full_name", "customer", "Name" %></th>
								<th>Phone</th>
								<th>Email</th>
								<th>In Quickbooks?</th>
								<th><%= sortable "needs_action", "customer", "Needs Action" %></th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							<% @customers.each do |customer| %>
								<tr class="<%= customer.needs_action ? 'warning' : '' %>">
									<td><%= link_to admin_customer_path(customer) do %><%= customer.full_name %><% end %></td>
									<td><%= customer.phone? ? number_to_phone(customer.phone) : "N/A" %></td>
									<td><%= customer.email? ? customer.email : "N/A" %></td>
									<td><%= customer.in_quickbooks ? "Yes" : "No" %></td>
									<td><%= customer.needs_action ? "<span class='glyphicon glyphicon-ok'></span>".html_safe : "<span class='glyphicon glyphicon-remove'></span>".html_safe %></td>
									<td>
										<%= link_to admin_customer_path(customer), action: "delete", class: "btn btn-warning" do %><span class='glyphicon glyphicon-remove'></span><% end %>
										<%= link_to edit_admin_customer_path(customer), class: "btn btn-primary" do %><span class='glyphicon glyphicon-pencil'></span><% end %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			<% end %>
		</div><!-- Col -->
	</div><!-- Row -->
</div>

app/views/admin/customers/new.html.erb
<div class="container">
	<div class="row">
		<h2>New Customer</h2>
	</div>
	<div class="row">
		<div id="content" class="col-md-12" style="margin-top: 25px">
			<%= flash_messages %>
		</div>
		<%= render "form" %>
	</div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<ol class="breadcrumb" style="text-align: left">
	      <li><%=link_to admin_customers_path do %>Customers<% end %></li>
	      <li class="active"><%= @customer.full_name %></li>
	    </ol>
	  </div>
		<div class="col-sm-12 col-md-6">
			<h2 style="margin-top: 0px"><%= @customer.full_name %>
			<% if @customer.needs_action -%>
				<span class="label label-warning" style="font-size: 0.5em">Alert</span>
			<% end -%>
			</h2>
		</div>
		<div class="col-sm-4 col-md-2">
			<%= link_to edit_admin_customer_path(@customer), class: "btn btn-default" do %>
				<span class="glyphicon glyphicon-pencil"></span>  Edit Customer
			<% end %>
		</div>
		<div class="col-sm-4 col-md-2">
			<%= link_to new_admin_customer_contact_path(@customer), class: "btn btn-primary" do %>
				<span class="glyphicon glyphicon-plus"></span>  New Contact
			<% end %>
		</div>
		<div class="col-sm-4 col-md-2">
			<%= link_to admin_customer_path(@customer), action: "delete", class: "btn btn-warning" do %>
				<span class="glyphicon glyphicon-remove"></span>  Delete Customer
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="well">
				<h4>Customer Information</h4>
				<p>
					<span style="font-weight: 700">Phone</span><br>
					<%= @customer.phone? ? @customer.phone : "N/A" %>
				</p>
				<p>
					<span style="font-weight: 700">Email</span><br>
					<%= @customer.email? ? @customer.email : "N/A" %>
				</p>
				<p>
					<span style="font-weight: 700">Vehicle</span><br>
					<%= @customer.vehicle? ? @customer.vehicle : "N/A" %>
				</p>
			</div>
		</div>

		<div class="col-sm-6 col-md-8">
			<h4>Notes and Parts Wanted</h4>
			<p><%= @customer.notes.html_safe %></p>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-sm-12 col-md-6">
			<h4>Previous Contacts</h4>
		</div>
		<%= search_form_for [:admin, @customer, @search_contacts], :url => admin_customer_path(@customer) do |f| %>
			<div class="col-sm-8 col-md-4">
				<div class="form-group">
					<%= f.text_field :jc_employee_cont, :size => 15, placeholder: "JC Employee Name", class: "form-control" %>
				</div>
			</div>
			<div class="col-sm-4 col-md-2">
				<%= f.submit "Search", class: "btn btn-default" %>
			</div>
		<% end %>

		<div id="content" class="col-md-12" style="margin-top: 25px">
   			<%= flash_messages %>
		</div>
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-striped" style="text-align: center">
					<thead>
						<tr>
							<th><%= sortable "date", "contact" %></th>
							<th>JC Employee</th>
							<th>Contact Method</th>
							<th>Notes</th>
							<th><%= sortable "resolved", "contact", "Actions" %></th>
						</tr>
					</thead>
					<tbody>
						<% @customer.contacts.each do |contact| %>
							<tr class='<%= contact.needs_action ? (contact.resolved ? "success" : "warning") : "" %>'>
								<td><%= contact.date.strftime("%m/%d/%Y") %></td>
								<td><%= contact.jc_employee %></td>
								<td><%= contact.method %></td>
								<td><%= contact.notes.html_safe %></td>
								<td>
									<% if contact.needs_action %>
										<%= link_to resolved_admin_customer_contact_path(@customer, contact), method: :put, data: { toggle: "tooltip", placement: "top"}, title: "Set to #{contact.resolved ? 'un' : '' }resolved", class: "btn btn-success" do %>
											<span class='glyphicon glyphicon-<%= contact.resolved ? "thumbs-down" : "thumbs-up" %>'></span>
										<% end %>
									<% end %>
									<%= link_to admin_customer_contact_path(@customer, contact), action: "delete", class: "btn btn-warning" do %>
										<span class='glyphicon glyphicon-remove'></span>
									<% end %>
									<%= link_to edit_admin_customer_contact_path(@customer, contact), class: "btn btn-primary" do %>
										<span class='glyphicon glyphicon-pencil'></span>
									<% end %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div><!-- Table-Responsive -->
		</div><!-- Col -->
	</div><!-- Row -->
</div>