config/routes.rb
Rails.application.routes.draw do

  get 'shop_images/show'

  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc

  Spree::Core::Engine.routes.draw do
  get 'shop_images/show'

  get 'qbwc/action' => 'qbwc#_generate_wsdl'
  get 'qbwc/qwc' => 'qbwc#qwc'
  wash_out :qbwc
    root to: "products#index"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount Spree::Core::Engine, :at => '/store'

  root :to => 'jcautohome#home'

  get "/admin" => redirect("/store/admin")

  get 'about' => 'jcautohome#about'
  get 'gallery' => 'jcautohome#gallery'
  get 'parts' => 'jcautohome#parts'
  get 'our-services' => 'jcautohome#services'
  get 'community' => 'jcautohome#community'
  get 'contact' => 'jcautohome#contact'
  get 'our-services/gauges' => 'jcautohome#gauges'
  get 'our-services/em' => 'jcautohome#em'
  get 'our-services/shipping' => 'jcautohome#shipping'
  get 'sale-cars' => 'jcautohome#sale_cars'
  get 'policies' => 'jcautohome#policies'
  get 'privacy-policy' => 'jcautohome#privacy_policy'
  get 'timeline' => 'jcautohome#timeline'
  get 'my-cars' => 'customer_cars#index'

  resources :services, only: :show
  resources :jcautohome do
    collection do
      post :submit_contact
    end
  end

  resources :cars, only: :show
  resources :sale_cars, only: :show
  resources :customer_cars, except: :show
  resources :shop_images, only: :show
  

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  namespace :admin do
    resources :customers do
      resources :contacts do
        member do
          put 'resolved'
        end
      end
    end

    resources :cars do
      resources :car_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :sale_cars do
      resources :sale_car_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :events do
      resources :event_images do
        collection do
          post :update_positions
        end
      end
    end

    resources :stories do
      resources :story_images
    end

    resources :services do
      resources :service_images
      resources :service_price_lists do
        collection do
          post :update_service_items_positions
        end
      end
    end

    resources :shop_images

    delete '/service_items/:id', to: "service_items#destroy", as: :service_item
  end

  resources :events, only: [:index, :show] do
    collection do
      post :event_rsvp
    end
  end

  resources :stories, only: [:index, :show]

  resources :user_events, only: [:create, :new]

end

app/models/service_image.rb
class ServiceImage < ActiveRecord::Base
	belongs_to :service
end

app/controllers/admin/service_images_controller.rb
class Admin::ServiceImagesController < AdminController
	before_action :load_service

	def new
		@image = ServiceImage.new
	end

	def create
    @image = @service.service_images.new(service_image_params)
    if @image.save
    	flash[:success] = "Image added successfully!"
      render "index"
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash[:error] = "Image unable to be saved.\n"
      flash[:error] += @image.errors.full_messages.join("\n")
      render "new"
    end
  end

  def edit
  	@image = ServiceImage.find(params[:id])
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    @image = ServiceImage.find(params[:id])
    respond_to do |format|
      if @image.update(car_image_params)
        flash[:success] = "Car Image was successfully updated."
        format.html { redirect_to admin_car_car_images_path(@image.car) }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	ServiceImage.find(params[:id]).destroy
    flash[:success] = "Image deleted"
    render "index"
  end

  def index
    @service = Service.find(params[:service_id])
  end

	private

	def load_service
    @service = Service.find(params[:service_id])
  end

  def car_image_params
	  params.require(:service_image).permit(:attachment, :attachment_file_name, :attachment_content_type, :attachment_file_size, :attachment_updated_at, :description)
	end
end

app/views/admin/service_images/_form.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @image } %>

<div data-hook="file" class="form-group">
  <%= f.label :image_path, Spree.t(:filename) %>
  <%= f.text_area :image_path %>
</div>
<div class="form-group">
  <%= f.label :description, Spree.t(:description) %>
  <%= f.text_area :description, :rows => 4, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= f.check_box :main_image %>
  <%= f.label :main_image, Spree.t(:main_image) %>
</div>
<div class="form-group">
	<%= f.check_box :thumb_image %>
  <%= f.label :thumb_image, Spree.t(:thumb_image) %>
</div>

app/views/admin/service_images/edit.html.erb
 <div class="container">
  <div class="row">
    <ol class="breadcrumb" style="text-align: left">
      <li><%=link_to admin_services_path do %>Services<% end %></li>
      <li><%=link_to edit_admin_service_path(@service) do %><%= @service.name %><% end %></li>
      <li><%=link_to admin_service_service_images_path(@service) do %>Images<% end %></li>
      <li class="active">New Image</li>
    </ol>
    <h2><%= @service.name %></h2>
    <h3><%= Spree.t(:edit_image) %></h3>

    <%= form_for [:admin, @service, @image], html: { multipart: true } do |f| %>
      <div data-hook="edit_image" class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= @image.description%>
          </h2>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <div data-hook="thumbnail" class="col-md-3 text-center">
              <%= f.label Spree.t(:thumbnail) %>
              <%= link_to image_tag(@image.image_path), @image.image_path %>
            </div>
            <div class="col-md-9">
              <%= render partial: 'form', locals: { f: f } %>
            </div>

            <div class="form-actions" data-hook="buttons">
              <%= button Spree.t('actions.update'), 'save' %>
              <span class="or"><%= Spree.t(:or) %></span>
              <%= button_link_to Spree.t('actions.cancel'), admin_service_service_images_path(@service), id: 'cancel_link', icon: 'delete' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/service_images/index.html.erb
<div class="container">
  <div class="row">
    <ol class="breadcrumb" style="text-align: left">
      <li><%=link_to admin_services_path do %>Services<% end %></li>
      <li><%=link_to edit_admin_service_path(@service) do %><%= @service.name %><% end %></li>
      <li class="active">Images</li>
    </ol>
    <div class="col-md-6">
      <h2><%= @service.name %></h2>
    </div>
    <div class="col-md-6" style="padding-top: 26px">
      <%= button_link_to("New Image", new_admin_service_service_image_path(@service), { class: "btn-success", icon: 'add', id: 'new_image_link' }) %>
      <%= button_link_to("Back to Service", edit_admin_service_path(@service), { class: "btn-info", icon: 'add' }) %>
    </div>
    <div id="content" class="col-md-12" style="margin-top: 25px">
      <%= flash_messages %>
    </div>
    <table class="table sortable" data-hook="images_table">
      <thead>
        <tr data-hook="images_header">
          <th colspan="2">
            <%= Spree.t(:thumbnail) %>
          </th>
          <th>
            <%= Spree.t(:alt_text) %>
          </th>
          <th>
            Main Image?
          </th>
          <th>
            Main Thumb?
          </th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% (@service.service_images).each do |image| %>
          <tr id="<%= spree_dom_id image %>" data-hook="images_row">
            <td class="image" colspan="2">
              <%= link_to image_tag(image.image_path), image.image_path %>
            </td>
            <td><%= image.description %></td>
            <td><%= image.main_image ? "Yes" : "No" %></td>
            <td><%= image.thumb_image ? "Yes" : "No" %></td>
            <td class="actions actions-2 text-right">
              <%= link_to(Spree.t(:edit), edit_admin_service_service_image_path(@service, image), :method => :get, class: 'btn btn-primary btn-sm') %>
              <%= link_to('delete', admin_service_service_image_path(@service, image),  data: { confirm: 'Are you sure?' }, :method => :delete, class: 'btn btn-warning btn-sm') %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div><!-- Container -->
</div><!-- Container -->

app/views/admin/service_images/new.html.erb
 <div class="container">
  <div class="row">
  	<ol class="breadcrumb" style="text-align: left">
      <li><%=link_to admin_services_path do %>Service<% end %></li>
      <li><%=link_to edit_admin_service_path(@service) do %><%= @service.name %><% end %></li>
      <li><%=link_to admin_service_service_images_path(@service) do %>Images<% end %></li>
      <li class="active">New Image</li>
    </ol>
  	<h2><%= @service.name %></h2>
    <h3><%= Spree.t(:new_image) %></h3>

		<%= form_for [:admin, @service, @image], html: { multipart: true } do |f| %>
	    <%= render partial: 'form', locals: { f: f } %>

	    <div class="form-actions" data-hook="buttons">
	      <%= button Spree.t('actions.update'), 'save' %>
	      <span class="or"><%= Spree.t(:or) %></span>
	      <%= button_link_to Spree.t('actions.cancel'), admin_service_service_images_path(@service), icon: 'delete', id: 'cancel_link' %>
	    </div>
		<% end %>
	</div>
</div>